### ISSUE TITLE
Add some unalowed nicknames

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/name_restrictions#1]
xorHub
XorHub
xorHub
Xorhub
XORHUB

MinetestForFun
MinetestforFun
MinetestForfun
Minetestforfun
minetestForFun
minetestforFun
minetestForfun
minetestforfun

etc...

(due to fake identity usage...)

**Comment by Lymkwi** [comment]
Isn't this issue completed?

**Comment by ObaniGemini** [comment]
I guess it will never be, there are always unallowed nicks to add.

**Comment by Lymkwi** [comment]
For now I only really care about those listed above. Did @crabman77 cover them all with his commits?

**Comment by ObaniGemini** [comment]
Laink, DarkLink, Terracid, Teracid, Teracide, Terracide, Amixem, Obani, ObaniGemini, etc..

**Comment by BetterToAutomateTheWorld** [comment]
Well, we add every month names to this list, i think we can close this issue

**Comment by Lymkwi** [comment]
Yo, what's the latest development here?

**Comment by ObaniGemini** [comment]
`none`

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium Well, we added many forbidden nicknames, i think it's enough, this issue isn't needed anymore

**Comment by Lymkwi** [comment]
Ok.
